### ISSUE TITLE
CLI Command Tracker

### ISSUE THREAD

**Issue by rushsteve1** [CarmeLabs/carme#2]
This issue is for tracking possible commands for the CLI and their function.
Please comment any additions or updates and I will update this list to reflect it.
- [x] `new <projectname>` creates project folder with `docker-compose.yml` inside
- [ ] `serve` starts the containers in`docker-compose.yml`
- [ ] `package` package management options
  - [ ] `add <packagename>` installs a package
  - [ ] `remove <packagename>` removes a package
  - [ ] `search <packagename>` searches for a package
- [ ] `info` gets info about install and current project

**Comment by jkuruzovich** [comment]
Funny....I had been creating the add cluster and module files for a while, but I gradually had come to the conclusion that we really need a simple package manager. You beat me there. ;) 

New should create a default directory structure that will be used to share data across containers. 
- input  (for data and other input files)
- dags (for sharing dags)

I've been going with the idea that there needs to be a launch.yaml in the directory to contain default config for packages and be editable all in one place.  This could include a list of packages installed. We could ask their email address and the project description when creating new and put in launch.yaml.

New should have options.
-- images.  This will copy image files into local directory for customizing. I've found I often have to do this. 
-- gpu. This will copy a version specific for a GPU. This will likely have a different image base. 

under packages.
  - [ ] `list`  lists available core packages
  -  [ ] `install`  install is consistent with conda.
  -  [ ] `upgrade`  upgrade is consistent with conda
- [ ] `info` gets info about install and current project (should we have a .carme file or something?)
- [ ] `<packagename> <command>` packages should have the ability to have their own commands.

Packages should have a package description file (keep as yaml).

**Comment by rushsteve1** [comment]
Relating to the directory structure I was thinking something like this:
```
project
   | --- docker/
   | --- data/
   | --- dags/
   | - config.yaml
```
`docker` holds docker-compose files and other docker related files.
`data` holds the user's data and is auto-mounted by Jupyter and other applications.
`dags` hold airflow dags
`config.yaml` is a project-wide configuration file.

**Comment by jkuruzovich** [comment]
Data works. 
I feel based on what I've seen `images` might be a bit more common. Default behavior shouldn't pull the images over.  That should be a flag option though.

**Comment by jkuruzovich** [comment]
@rushsteve1 Suggest to close, as I think covered by other issues.
