### ISSUE TITLE
Refactoring tracker

### ISSUE THREAD

**Issue by dmccrevan** [CarmeLabs/carme#48]
#This is just a tracker for good refactoring ideas
- [ ] Move all yaml functionality from the CLI commands to the `yamltools` package
- [ ] Change all variables to snake case
- [ ] Change function docstrings to style like `gitwrapper`

**Comment by rushsteve1** [comment]
Superseded by #56
